# Generated by Django 4.2.7 on 2023-12-10 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imagenes',
            table='map_imagenes',
        ),
        migrations.AlterModelTable(
            name='operador',
            table='map_operador',
        ),
        migrations.AlterModelTable(
            name='ubicaciones',
            table='map_ubicaciones',
        ),
        migrations.AlterModelTable(
            name='vuelo',
            table='map_vuelo',
        ),
    ]
