# Generated by Django 4.1.12 on 2023-10-25 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_vuelo'),
    ]

    operations = [
    ]
