# Generated by Django 4.1.12 on 2023-10-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20231024_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vuelo',
            old_name='crate_at',
            new_name='create_at',
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='este',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='norte',
            field=models.FloatField(),
        ),
        migrations.AlterModelTable(
            name='vuelo',
            table='vuelo',
        ),
    ]
