# Generated by Django 4.2.7 on 2023-12-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_imagenes_table_alter_operador_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes',
            name='nombre_imagen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
