# Generated by Django 4.1.12 on 2023-10-26 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_rename_crate_at_vuelo_create_at_alter_vuelo_este_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Ubicacion')),
                ('latitud', models.FloatField(verbose_name='Latitud')),
                ('longitud', models.FloatField(verbose_name='Longitud')),
                ('poblacion_ubicada', models.CharField(max_length=250, verbose_name='Poblacion Ubicada')),
                ('id_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.vuelo')),
            ],
            options={
                'verbose_name': 'Ubicacion',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicacion',
                'ordering': ['id_ubicacion'],
            },
        ),
    ]
