# Generated by Django 4.2.7 on 2023-12-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_imagenes_nombre_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='analizada',
            field=models.BooleanField(default=False),
        ),
    ]
