# Generated by Django 4.1.12 on 2023-11-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploaded_images/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=255)),
                ('flight_number', models.IntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('analysis_date', models.DateTimeField(blank=True, null=True)),
                ('detected_tree_type', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
