# Generated by Django 4.2.7 on 2023-12-11 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_imagenes_analizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='cantidad_imagenes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='cantidad_predicciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.operador'),
        ),
    ]
