# Generated by Django 4.1.12 on 2023-11-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_imagedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muestreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_vuelo', models.CharField(max_length=50)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('direccion', models.CharField(max_length=255)),
                ('fecha_muestreo', models.DateTimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'muestreo',
            },
        ),
        migrations.DeleteModel(
            name='ImageData',
        ),
    ]
