# Generated by Django 4.2.7 on 2023-12-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_alter_imagenes_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenes',
            name='image_url',
        ),
        migrations.AddField(
            model_name='imagenes',
            name='resultado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
