# Generated by Django 4.2.7 on 2023-12-19 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_remove_imagenes_image_url_imagenes_resultado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicaciones',
            name='numero_asignacion',
        ),
        migrations.AddField(
            model_name='ubicaciones',
            name='vuelos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.vuelo'),
        ),
    ]
