# Generated by Django 4.2.7 on 2023-12-19 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_remove_ubicaciones_numero_asignacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='ubicaciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.ubicaciones'),
        ),
    ]
