# Generated by Django 4.2.7 on 2023-12-19 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_imagenes_ubicaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='map.ubicaciones'),
        ),
    ]
