# Generated by Django 4.2.7 on 2023-12-19 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_vuelo_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenes',
            name='ubicaciones',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='ubicacion',
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='vuelos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.vuelo'),
        ),
    ]
