# Generated by Django 4.2.7 on 2023-12-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_remove_imagenes_ubicacion_remove_ubicaciones_latitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vuelo',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='vuelo',
            name='longitud',
        ),
        migrations.AddField(
            model_name='imagenes',
            name='latitud',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='imagenes',
            name='longitud',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='numero_asignacion',
            field=models.IntegerField(),
        ),
    ]
