# Generated by Django 4.2.7 on 2023-12-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0018_remove_vuelo_latitud_remove_vuelo_longitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicaciones',
            name='numero_asignacion',
            field=models.IntegerField(null=True),
        ),
    ]
