# Generated by Django 4.2.7 on 2023-12-19 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_alter_ubicaciones_vuelos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenes',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='imagenes',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='ubicaciones',
            name='numero_asignacion',
        ),
        migrations.AddField(
            model_name='vuelo',
            name='latitud',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='longitud',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ubicaciones',
            name='vuelos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.vuelo'),
        ),
    ]
