# Generated by Django 4.2.7 on 2023-12-19 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0021_remove_imagenes_latitud_remove_imagenes_longitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicaciones',
            name='vuelos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.vuelo'),
        ),
    ]
