# Generated by Django 4.2.7 on 2023-12-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0022_alter_ubicaciones_vuelos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicaciones',
            name='vuelos',
        ),
        migrations.AddField(
            model_name='ubicaciones',
            name='direccion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
