# Generated by Django 4.2.7 on 2023-12-19 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0023_remove_ubicaciones_vuelos_ubicaciones_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicaciones',
            name='vuelo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.vuelo'),
        ),
    ]
