# Generated by Django 4.2.7 on 2023-12-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0024_ubicaciones_vuelo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='porcentaje_prediccion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
