# Generated by Django 4.2.7 on 2023-12-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0025_imagenes_porcentaje_prediccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuelo',
            name='cantidad_imagenes_nuevas',
            field=models.IntegerField(default=0),
        ),
    ]
