# Generated by Django 4.2.7 on 2023-12-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0026_vuelo_cantidad_imagenes_nuevas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaMuestreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=12)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
        ),
    ]
