# Generated by Django 4.2.7 on 2023-12-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0027_areamuestreo'),
    ]

    operations = [
        migrations.AddField(
            model_name='areamuestreo',
            name='detecciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='areamuestreo',
            name='especieArbol',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='areamuestreo',
            table='map_areaMuestreo',
        ),
    ]
