# Generated by Django 4.2.7 on 2023-12-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0028_areamuestreo_detecciones_areamuestreo_especiearbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areamuestreo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
